### ISSUE TITLE
Refactor all indexer code to use result types

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy-indexer#15]

**Comment by LukasDeco** [comment]
try refactoring some of the code to use the rust style result types similar to what I'm doing [here](https://github.com/metaDAOproject/futarchy-indexer/blob/ad26dea8624384b87d23cab849b7f2ec5764fb68/packages/indexer/src/transaction/serializer.ts#L95-L140) and [here](https://github.com/metaDAOproject/futarchy-indexer/blob/ad26dea8624384b87d23cab849b7f2ec5764fb68/packages/indexer/src/transaction/account-resolver.ts#L5-L26)
