### ISSUE TITLE
Create CRUD API for Creating DAOs / Proposals

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy-indexer#25]
`x-hasura-user-role` has been setup for `dao_details` and `proposal_details` which affords mutations on JUST THOSE TABLES

These user roles are `creator` for dao_details and `proposer` for proposal_details.

Using mutations with graphql you should be able to insert the corresponding data:

`dao_details`
dao_id (we need to generate this or update the table to use AI)
name
x_account
github
description
slug
image_url

`proposal_details`
proposal_id (we need to generate this or update the table to use AI)
proposal_acct (need to revisit this due to the fact that we may not have it generated yet)
title
description (unused, but thought maybe summary)
categories (jsonb)
content (markdown)
slug (taken from title)

**Comment by R-K-H** [comment]
We can access these through Hasura, which means that we should be able to move quickly once we get updates to the table @decartesol I'm blocked with updating tables until I understand a bit more with drizzle and what we want / can do.

**Comment by decartesol** [comment]
We don't want a create for these. The indexer will auto create these when it encounters the corresponding instructions

**Comment by R-K-H** [comment]
The issue is that some of the data is not on chain. So the UI will accept fields like twitter url or for a proposal markdown content, which in turn when "creating" the proposal ON CHAIN will wait for txn to process, then insert the data into the DB for the new proposal or DAO, we could wait for indexer or whatever, but ideally we're supplementing what we have here with enriched off chain data and want to be flexible while we test things out.


Then move to on chain as much as we can (to own the primitive). Not sure how markdown will work... But some of it could.

**Comment by R-K-H** [comment]
Removing myself and moving to backlog. @decartesol if I'm wrong in assuming that you said this is on your list LMK.

**Comment by R-K-H** [comment]
`x-hasura-user-role` has been setup for `dao_details` and `proposal_details` which affords mutations on JUST THOSE TABLES

These user roles are `creator` for dao_details and `proposer` for proposal_details.
