### ISSUE TITLE
Add created_at, slot_per_proposal

### ISSUE THREAD

**Issue by swaggymarie** [metaDAOproject/futarchy-indexer#59]
There is a updated_at key in the proposals tabs but not created_at
Then, to get the proposal finalization date from the creation date, we need to add the slot_per_proposal variable into the dao table

**Comment by R-K-H** [comment]
Just a note here. The older versions just had a fixed constant in the program code, so we can just use that for the old daos (MetaDAO) on mainnet.

**Comment by R-K-H** [comment]
See: https://github.com/metaDAOproject/futarchy-indexer/pull/66
