### ISSUE TITLE
Setup Prometheus, Grafana

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy-indexer#6]

**Comment by LukasDeco** [comment]
having an issue setting up the metrics exposer for prometheus in this bun application due to a long-standing compatibility issue with bun and prometheus:  https://github.com/oven-sh/bun/pull/8239

**Comment by R-K-H** [comment]
Maybe this fixes it? https://github.com/siimon/prom-client/pull/599 not saying it's good, but this is data reporting so not something that's live with folks.
